### PR TITLE
Changed hello world text 

### PR DESCRIPTION
**Pull request by MantsSk**
Changed hello world text:

Hello world text was changed, a few lines deleted

### CODE REVIEW

**Review by MDovydas — CHANGES_REQUESTED** [review]
OK, bet vien eilut eperdaug

**Comment by MutagenSnake** [comment]
Ai, normaliai.

**Review by MutagenSnake — COMMENTED** [review]
Ok

**Review by EGO1ST77 — COMMENTED** [review]
OK, tinka

**Pull request merged**
